### ISSUE TITLE
Cannot switch direction of a connection

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#101]
I accidentally created a feature group connection from the destination to the source. It would be helpful to have an operation in the context menu to switch the direction. Currently I have to do it in the text editor.

**Comment by philip-alldredge** [comment]
8f5c960b2ba4142b5038a2ec908aa4eec6664366 adds a menu to switch the direction of the connection. It currently does not perform validation to determine whether the swapped connection will be valid because there are several complex cases. In the future, validation could be added but that would likely involve considerably more effort.
