### ISSUE TITLE
Flow editing dialog not resizable

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#115]
On Kubuntu 15.04: It is impossible to add a segment to a flow in my environment because (I assume) the insert button is drawn outside the visible area. The only thing I can do is delete segments or add the forst segment to a flow after that there's no insert button. The dialog must be resizable to show the complete content. Also, all eclipse dialogs are resizable, so the same should be true in osate. 

The image shows the dialog with the example model from #osate/osate2-core/598, invoked using "Edit flows..." in the playerProcess.impl diagram.

![snapshot1](https://cloud.githubusercontent.com/assets/750311/9007801/edfc5bd4-3762-11e5-82c3-043d6502ed51.png)

**Comment by philip-alldredge** [comment]
Thanks for reporting this. Part of the problem was that the dialog itself wasn't being layed out properly so the buttons weren't visible. The other issue is the dialog wasn't resizable. Both have been fixed in 485ea30edafecf5ddc2c9ab72d379e140de3cb04. The dialog should now be resizable and make full use of the available space. I haven't tested this under linux but the problem should be fixed.
