### ISSUE TITLE
import java.util.Objects not found

### ISSUE THREAD

**Issue by brlarson** [osate/osate-ge#117]
Goofy error on current pull of OSATE git
To fix:
Change project org.osate.ge => Properties => Java Bulid Path => Libraries tab
delete the 1.6 JRE System Library and replace it with Java SE 8 [1.8.x]

**Comment by brlarson** [comment]
I tried to commit and push the change, but got and error:   https://github.com/osate/osate-ge.git: git-receive-pack not permitted

**Comment by philip-alldredge** [comment]
Yes, we started using some of the classes in Java 8, but didn't update the project settings. Since we didn't have a older java compiler installed, we haven't been getting the error. I just pushed a change. Thank you for making me aware of the problem.

Fixed by d74245e44df9a5ccf1117128a19a5af88ae4f403.
