### ISSUE TITLE
Subcomponent cannot be resized if it is covered by labels

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#171]
It is possible that the image of a subcomponent is completely covered with labels of ports/connections/name such that it cannot be resized in the graphical editor. In this particular case a user increased the nesting level and was unable to select a subcomponent. He always hit a label. instead.

**Comment by philip-alldredge** [comment]
In the short-term, we will add a command to the context menu that will select the parent of the selected object.

We also plan to add outline support(#106). That will make it easier to select the desired object.

**Comment by philip-alldredge** [comment]
A "Select Container" command has been pushed to the develop branch. In cases where the user is unable to select a shape due to the children being in the way, the user can now use the Select Container command to select the desired shape. 

The Layout Diagram command also provides a way to work around the issue, but is often not desired since it will reset the positions of all shapes in the diagram.

Once outline view support is implemented(#106 ), that will provide an alternative way of selecting shapes.

**Comment by philip-alldredge** [comment]
Closing.

**Comment by philip-alldredge** [comment]
Additional work around: The Alt-Up and Alt-Down keyboard shortcuts can be used to navigate the diagram hierarchy.
