### ISSUE TITLE
Hide package name when not needed

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate-ge#220]
The fully qualified package name for each component is generally not needed unless the component has been imported from a different package. For visual clarity, the package name should be hidden by default.

This is the behavior in Enterprise Architect.

**Comment by philip-alldredge** [comment]
Are you referring to just subcomponents or are there other cases where this is happening?

**Comment by smithdtyler** [comment]
I think I've seen it in a few places, in the example below it's in the name of the implemented type. 

![screen shot 2017-10-02 at 4 40 10 pm](https://user-images.githubusercontent.com/8142684/31100777-6638a0fe-a790-11e7-836f-73b93dfbb464.png)

**Comment by philip-alldredge** [comment]
Okay. Thanks for the clarification.

**Comment by philip-alldredge** [comment]
Fixed in 24199d029a52c60eaff4e07d19a0118753cb3ebb. For subcomponent types the qualified name will be used if the type is not in the same package as the top level component implementation. I'm not sure this is the best behavior but it will allow usage so we can decide whether the behavior needs to be refined. For generalizations the qualified name will be shown if the general and specific elements are not in the same package.
