### ISSUE TITLE
Clean arrow end presentation

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate-ge#225]
The endings of lines between components meant to show directionality often end up pointing in a direction that visually conflicts with their line.

![screen shot 2017-10-02 at 4 20 52 pm](https://user-images.githubusercontent.com/8142684/31100063-b30ec780-a78d-11e7-86cd-3fdd91392ed7.png)

There are a couple of ways to address this:
1. Automatically display connections as the shortest possible line between the components. In the screenshot below, the connection was automatically positioned at the left edge of pasta, despite its other end sitting off to the right. 

![screen shot 2017-10-02 at 4 15 34 pm](https://user-images.githubusercontent.com/8142684/31099978-682b55f8-a78d-11e7-9b05-0c87b26ac5ea.png)

2. Add a vertex in the line to allow it to fit the natural orientation of the ending arrow (manually added below).

![screen shot 2017-10-02 at 4 22 41 pm](https://user-images.githubusercontent.com/8142684/31100140-f9f5196a-a78d-11e7-83e4-82a87ee3d116.png)

3. Use a different icon for "start of outgoing connection" as "end of incoming flow", the former being much smaller than the latter.

**Comment by philip-alldredge** [comment]
The line endings shown are showing the direction of the port and not the connection. I agree that improved automatic layout would help in cases such as this. We are working to improve the default layout of diagrams.

Can you clarify "3."?

**Comment by smithdtyler** [comment]
For number 3, my confusion is that the icon for "incoming" port is the same icon as "outgoing" port, just rotated 180 degrees. I think it would be clearer if the incoming icon was distinct from the outgoing regardless of orientation (i.e. no rotational symmetry). It could be a different color, different shape, or different size. 

I don't really think outgoing ports should need an icon at all (I'd rather just trace the arrow visually to determine that it's outgoing based on the icon at the other end), but if outgoing ports need an icon, I'd rather they have something that doesn't intrude as much on the real estate of the component. Simply reusing the "orientation" icon that sits at the middle of the connection would be sufficient:

![screen shot 2017-10-03 at 9 16 26 am](https://user-images.githubusercontent.com/8142684/31129945-a98f8d00-a81b-11e7-8966-5f7c44a6040e.png)

**Comment by philip-alldredge** [comment]
The graphical representation is intentional. The graphics are specified in the AADL standard and we try to follow those in most cases.

I personally am a fan of the symmetry/similarity between in, out, and in/out ports, but this may be something you can propose of the committee if you have suggestions for how the graphics for ports could be improved.

As far as not needing outgoing ports in the diagram at all... I'll have to strongly disagree with that. For some visualization purposes it may not be critical but for editing and many other purposes, the output ports and their labels are critical to understanding the model. 

However, specific subcomponents can be configured to hide particular ports. This can be done by checking the sub-component and selecting minimal. In that case, you'll have to check all the subcomponent's children that should be included in the diagram. However, the graphical representation of the connection will change. It will no longer be a solid line to indicate that what is being shown does not directly represent the AADL model. We are planning on refining the diagram configuration dialog as part of #211 so any thoughts you have on what preset rules you would like to see would be helpful.

On a related note, what are your thoughts on connection labels? I feel they get in the way quite a bit and I was wondering if adding options to hide such labels could be beneficial. Thoughts?

**Comment by smithdtyler** [comment]
> On a related note, what are your thoughts on connection labels? I feel they get in the way quite a bit and I was wondering if adding options to hide such labels could be beneficial. Thoughts?

I would definitely like this feature, especially since the label I most often assign to connections is just the names of the two components.

**Comment by philip-alldredge** [comment]
The symbols of the ports will not be changed. However, #229 makes the direction more obvious. Additionally, once #158 is implemented the layout algorithm will layout the diagram in such a way that such intersections do not occur. Closing
