### ISSUE TITLE
Dirty marker doesn't disappear when undo-ing all changes in graphical editor

### ISSUE THREAD

**Issue by lwrage** [osate/osate-ge#283]
Open a diagram, resize a component, hit undo. The diagram looks the same as before but the diagram is still marked as dirty.
Maybe a check of the undo stack needs to be added?

**Comment by philip-alldredge** [comment]
This will need to be addressed when the Undo and Redo support is reworked. The current dirty indicator just sets the flag when something is changed. This resolved the previous issue but does not result in the flag being cleared as part of the undo.

Getting useful information from the undo stack is tricky because it includes things that don't result in a diagram change. This was the root cause of the dirty indicator constantly being reset. 

This needs to be worked in conjunction with #216
