### ISSUE TITLE
flow specification creation

### ISSUE THREAD

**Issue by reteprelief** [osate/osate-ge#81]
It would be nice to declare flow specs graphically similar to connections.
For consistency would want to do that for source and sink as well - just select one port.

**Comment by philip-alldredge** [comment]
I believe the best approach is to modify the current menu options to be in the palette rather than in the menu item.

Modify CreateSimpleFlowSpecificationFeature to inherit from AbstractCreateFeature. Remove and modify methods as approach to implement the create feature. Update the feature provider to use the create feature in the appropriate way. The palette icon and label will need to change based on the type of feature. It should be categorized so it appears in the Flow section of the palette.

**Comment by philip-alldredge** [comment]
Implemented in 495c0a4f8b936a7e931016bfabdd73d96908031d.
