### ISSUE TITLE
Performance when editing several models

### ISSUE THREAD

**Issue by juli1** [osate/osate-ge#93]
When editing a model with several projects together, the editor is very slow. Closing the projects currently open improves the performance. I am guessing there are some methods that invoke code to validate/check other unrelated projects and slow down the editor significantly.

**Comment by philip-alldredge** [comment]
Julien,
I've been working to try to address some of the performance issues. I believe this one is related to the editor trying to update things when editing has occurred. It has been partially addressed in 7fa7e6a8bda7b18f175139204f782cdb72dc2583. There is still more work to do. Unfortunately, it may results in some undesired behavior because it will no longer open diagrams to make changes in the background but I believe having a scalable solution is the important thing. I'll keep this open until the remainder of the changes are implemented.
